fixes #829 - Add null string check and optional error message for apoc.spatial.geocode* functons
larusba/neo4j-apoc-procedures pull request #2
Opened 2018-07-27 12:43 UTC by AngeloBusato

2018-07-27 13:59 UTC, inserpio requested changes

2018-07-27 13:59 UTC, inserpio commented on src/main/java/apoc/spatial/Geocode.java
> +    public void checkNullOrEmptyAddress(String address){
static

2018-07-27 13:59 UTC, inserpio commented on src/test/java/apoc/spatial/SpatialTest.java
> +        public void checkNullOrEmptyAddress(String address){
static

2018-07-27 13:59 UTC, inserpio commented on src/test/java/apoc/spatial/SpatialTest.java
> +        public void checkNullOrEmptyAddress(String address){
or call `Geocode. checkNullOrEmptyAddress `

2018-07-31 14:33 UTC, albertodelazzari approved these changes

2018-07-31 14:33 UTC, albertodelazzari commented on src/main/java/apoc/spatial/Geocode.java
> +        if (address == null || address.isEmpty() || address.equals(""))
address.isEmpty() == address.equals("") because "".length() == 0

2018-07-31 14:35 UTC, merged