fixes #816 - requesting ability to bury url for apoc.load.json into neo4j.conf
larusba/neo4j-apoc-procedures pull request #22
Opened 2018-11-09 14:27 UTC by AngeloBusato

2018-11-09 14:43 UTC, conker84 requested changes

2018-11-09 14:43 UTC, conker84 commented on src/test/java/apoc/load/JdbcTest.java
> +    @Test(expected = RuntimeException.class)
Per favore testiamo che l'eccezione torni il messaggio corretto come fatto [quì](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/4e6009825bef8dba5bafdf39686db745028c0fea/src/test/java/apoc/load/XmlTest.java#L349)

2018-11-09 14:43 UTC, conker84 commented on src/main/java/apoc/load/LoadJson.java
>  public class LoadJson {
ma gli altri metodi non dovrebbero essere ugualmente gestiti? Mi risulta che posso passare url anche con una semplice `apoc.load.json`. Per favore aggiungere se si tratta di una dimenticanza

2018-11-09 16:15 UTC, AngeloBusato commented
@conker84 aggiornata

2018-11-12 09:55 UTC, conker84 approved these changes

2018-11-12 09:55 UTC, conker84 commented
Ok procedi con la PR

2018-11-12 10:04 UTC, closed without merging