fixes #994 - Provide a configuration parameter map with user/pass for JDBC
larusba/neo4j-apoc-procedures pull request #28
Opened 2018-11-19 16:14 UTC by AngeloBusato

2018-11-19 17:19 UTC, conker84 requested changes

2018-11-19 17:19 UTC, conker84 commented on src/test/java/apoc/load/JdbcTest.java
> +    private static final String TEST_WITH_AUTHENTICATION = "Authentication";
```suggestion
    private static final String TEST_WITH_AUTHENTICATION = "WithAuthentication";
```

2018-11-19 17:19 UTC, conker84 commented on src/test/java/apoc/load/JdbcTest.java
> +    private java.sql.Date hireDate = new java.sql.Date( new Calendar.Builder().setDate(2017, 04, 25).build().getTimeInMillis() );
tutte le variabli di tipo data e tempo spossiamo rimetterle statiche anzi aggiungiamo anche final

2018-11-19 17:19 UTC, conker84 commented on src/main/java/apoc/load/util/LoadJdbcConfig.java
> +        this.credentials = (Map<String, Object>) config.getOrDefault("credentials",Collections.emptyMap());
Aggiungere una validazione a credentials, se non ha username o password (o se sono vuote) deve tornare una `IllegalArgumentException` inoltre aggiungere un test dove testiamo questa eccezione

2018-11-20 14:22 UTC, conker84 requested changes

2018-11-20 14:22 UTC, conker84 commented on src/main/java/apoc/load/util/LoadJdbcConfig.java
> +        if (!credentials.get("user").equals("") && credentials.get("user") != null && !credentials.get("password").equals("") && credentials.get("password") != null) {
Così com'è potrebbe dare `NullPointerException` in caso non ci sia una chiave, ovvero in caso sia `{user: 'foo'}` o `{user: ''}` o `{password: 'bar'}` o `{password: ''}`

```suggestion
        if (credentials.getOrDefault("user", StringUtils.EMPTY).equals(StringUtils.EMPTY) || credentials.getOrDefault("password", StringUtils.EMPTY).equals(StringUtils.EMPTY)) {
```
Cerchiamo sempre di utilizzare **Costanti** tipo `StringUtils.EMPTY`...

2018-11-20 14:22 UTC, conker84 commented on src/main/java/apoc/load/util/LoadJdbcConfig.java
> +    private Map<String,Object> credentials;
Non si può mettere come di seguito?
```suggestion
    private Map<String, String> credentials;
```
e togliere i vari `toString`

2018-11-20 14:22 UTC, conker84 commented on docs/loadjdbc.adoc
> +CALL apoc.load.jdbcUpdate('jdbc:derby:derbyDB','UPDATE PERSON SET NAME = ? WHERE NAME = ?',['John','John'],{credentials:{user:'apoc',password:'Ap0c!#Db'}})
Documentare bene che si può fare in entrambi i modi sia come hai scritto tu, sia così:
`jdbc:derby:derbyDB;user=apoc;password=Ap0c!#Db;create=true`

2018-11-20 14:39 UTC, AngeloBusato commented
@conker84 aggiornata

2018-11-20 17:20 UTC, conker84 requested changes

2018-11-20 17:20 UTC, conker84 commented on src/test/java/apoc/load/JdbcTest.java
>          db = new TestGraphDatabaseFactory().newImpermanentDatabase();
```suggestion
        db = apocGraphDatabaseBuilder();
```

2018-11-20 17:20 UTC, conker84 commented on src/test/java/apoc/load/JdbcTest.java
>          db.shutdown();
Manca la parte di teardown di DerbyDB:
```suggestion
        db.shutdown();
        conn.close();
        try {
            if (testName.getMethodName().endsWith(TEST_WITH_AUTHENTICATION)) {
                DriverManager.getConnection("jdbc:derby:derbyDB;user=apoc;password=Ap0c!#Db;shutdown=true");
            } else {
                DriverManager.getConnection("jdbc:derby:derbyDB;shutdown=true");
            }
        } catch (SQLException e) {
            // DerbyDB shutdown always raise a SQLException, see: http://db.apache.org/derby/docs/10.14/devguide/tdevdvlp20349.html
            if (((e.getErrorCode() == 45000)
                    && ("08006".equals(e.getSQLState())))) {
                // Note that for single database shutdown, the expected
                // SQL state is "08006", and the error code is 45000.
            } else {
                throw e;
            }
        }
        System.clearProperty("derby.connection.requireAuthentication");
        System.clearProperty("derby.user.apoc");
```

`conn` è una variablie privata della classe di tipo `private Connection conn;` toglierla alla riga 204

2018-11-20 17:20 UTC, conker84 commented on src/test/java/apoc/load/JdbcTest.java
>          Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
```suggestion
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver").newInstance(); // The JDBC specification does not recommend calling newInstance(), but adding a newInstance() call guarantees that Derby will be booted on any JVM. See: http://db.apache.org/derby/docs/10.14/devguide/tdevdvlp20349.html
```

2018-11-20 17:20 UTC, conker84 commented on src/test/java/apoc/load/JdbcTest.java
> +           conn = DriverManager.getConnection("jdbc:derby:derbyDB;create=true", new Properties());
```suggestion
           conn = DriverManager.getConnection("jdbc:derby:derbyDB;create=true");
```

2018-11-20 17:21 UTC, conker84 commented on src/test/java/apoc/load/JdbcTest.java
> +           conn = DriverManager.getConnection("jdbc:derby:derbyDB;create=true", new Properties());
Occhio anche all'indentazione e lo spazio prima dell'`else`

2018-11-21 09:32 UTC, AngeloBusato commented
@conker84 aggiornata

2018-11-21 15:48 UTC, conker84 approved these changes

2018-11-21 15:48 UTC, conker84 commented
Ok procedi grazie mille!

2018-11-21 15:58 UTC, closed without merging