fixes #721 - GraphML import and labels
larusba/neo4j-apoc-procedures pull request #36
Opened 2018-12-07 15:39 UTC by AngeloBusato

2018-12-14 15:15 UTC, conker84 requested changes

2018-12-14 15:15 UTC, conker84 commented on src/test/java/apoc/export/graphml/ExportGraphMLTest.java
> +    @Before
Perché abbiamo fatto questo cambiamento?

2018-12-17 14:47 UTC, mzaratin-larus commented on src/test/java/apoc/export/graphml/ExportGraphMLTest.java
> +    @Before
Ho tolto il cambiamento, effettivamente non aveva senso

2018-12-17 15:05 UTC, mzaratin-larus commented on src/test/java/apoc/export/graphml/ExportGraphMLTest.java
> +    @Before
Perchè devo andare a verificare per ogni test chiamato il nome del metodo
   `private static final String TEST_WITH_NO_IMPORT = "WithNoImportConfig";
    private static final String TEST_WITH_NO_EXPORT = "WithNoExportConfig"; `

    `@Before
    public void setUp() throws Exception {
        GraphDatabaseBuilder builder  = new TestGraphDatabaseFactory()
                .newImpermanentDatabaseBuilder()
                .setConfig(GraphDatabaseSettings.load_csv_file_url_root, directory.getAbsolutePath());
        if (!testName.getMethodName().endsWith(TEST_WITH_NO_EXPORT)) {
            builder.setConfig("apoc.export.file.enabled", "true");
        }
        if (!testName.getMethodName().endsWith(TEST_WITH_NO_IMPORT)) {
            builder.setConfig("apoc.import.file.enabled", "true");
        }
        db = builder.newGraphDatabase();
        TestUtil.registerProcedure(db, ExportGraphML.class, Graphs.class);
        db.execute("CREATE (f:Foo:Foo2:Foo0 {name:'foo'})-[:KNOWS]->(b:Bar {name:'bar',age:42}),(c:Bar {age:12,values:[1,2,3]})").close();
    }`

2018-12-19 08:24 UTC, conker84 requested changes
Correggere il nome, rifare test per vedere se è tutto verde e in caso positivo pushare

2018-12-19 08:24 UTC, conker84 commented on src/test/java/apoc/export/graphml/ExportGraphMLTest.java
> +    private static final String EXPEDTED_READ_NODE_EDGE = String.format(HEADER + GRAPH + DATA_NODE_EDGE + FOOTER);
EXPEDTED_READ_NODE_EDGE -> EXPECTED_READ_NODE_EDGE

2018-12-19 08:24 UTC, conker84 commented
Grazie mille!

2018-12-19 09:02 UTC, mzaratin-larus commented
@conker84 PR aggiornata

2018-12-19 14:32 UTC, conker84 approved these changes

2018-12-19 14:32 UTC, conker84 commented
Grazie mille. Procedere!

2018-12-19 16:25 UTC, closed without merging