Issue 478 bis
larusba/neo4j-apoc-procedures pull request #37
Opened 2018-12-11 11:01 UTC by AngeloBusato

2018-12-14 15:23 UTC, conker84 requested changes

2018-12-14 15:23 UTC, conker84 commented on src/main/java/apoc/export/util/ExportConfig.java
> +    private Object caption;
```suggestion
    private String[] caption;
```
e cambiare tutto di conseguenza, quindi il metodo `convertCaption` metterlo qui dentro

2018-12-14 15:23 UTC, conker84 commented on src/main/java/apoc/export/util/MetaInformation.java
> +                return "integer".equals(name) || !isAllowed ? "int" : name;
`!isAllowed` è necessario?

2018-12-14 15:23 UTC, conker84 commented on src/main/java/apoc/export/graphml/XmlGraphMLWriter.java
> +        String labelsString = config.getCaption() == null ? getLabelsString(node) : GephiFormatUtils.caption(node, convertCaption(config.getCaption()));
passa config a `getLabelsString` gestisci tutto li dentro

2018-12-14 16:00 UTC, conker84 requested changes

2018-12-14 16:00 UTC, conker84 commented on src/main/java/apoc/export/util/ExportConfig.java
> +    public String getFormatGephi() { return formatGephi; }
per favore aggiungi un valore all'enum `ExportFormat` di tipo GEPHI

2018-12-14 16:00 UTC, conker84 commented on src/main/java/apoc/export/util/ExportConfig.java
> +    public String getFormatGephi() { return formatGephi; }
e rimuovi `formatGephi`

2018-12-17 14:12 UTC, mzaratin-larus commented on src/main/java/apoc/export/util/MetaInformation.java
> +                return "integer".equals(name) || !isAllowed ? "int" : name;
Si perchè altrimenti non verrebbero gestiti i casi di Long e Double

2018-12-17 14:50 UTC, mzaratin-larus commented on src/main/java/apoc/export/util/MetaInformation.java
> +                return "integer".equals(name) || !isAllowed ? "int" : name;
Si perchè altrimenti, prendiamo il caso di una lista di Long senza quel `!isallowed` la lista verrebbe vista come una lista di Stringa e non di Long

2018-12-18 13:31 UTC, mzaratin-larus commented
![edges](https://user-images.githubusercontent.com/12963830/50157396-956ed580-02d1-11e9-95b2-c7b09fb268b6.png)
![nodes](https://user-images.githubusercontent.com/12963830/50157397-956ed580-02d1-11e9-8703-0b50d2b82d21.png)

2018-12-19 08:36 UTC, conker84 requested changes

2018-12-19 08:36 UTC, conker84 commented on src/main/java/apoc/export/util/FormatUtils.java
> +    public static String formatPoint (Point value) {
```suggestion
     public static String formatPoint(Point value) {
```

2018-12-19 08:36 UTC, conker84 commented on docs/overview.adoc
> +All `Point` or `Temporal` data types are exported formatted as a String
Manca tutta la documentazione di come funziona `export: Gephi` e `caption`

2018-12-19 08:36 UTC, conker84 commented on src/main/java/apoc/export/util/MetaInformation.java
> +        if (config.getCaption() == null) {
```suggestion
         String[] caption = config.getCaption()
         if (caption == null || caption.length) {
```

2018-12-19 10:52 UTC, mzaratin-larus commented
@conker84 Pr aggiornata

2018-12-19 14:34 UTC, conker84 approved these changes

2018-12-19 14:43 UTC, conker84 requested changes

2018-12-19 14:43 UTC, conker84 commented on docs/overview.adoc
> +| caption | | Array of Strings, eg. ['name','title']. If no property was found set the ID. Otherwise set the property to `Label` column
```suggestion
 | caption | | It's an array of string (i.e. ['name','title']) that define an ordered set of properties eligible as value for the `Label` value, if no match is found the there is a fallback to the node label, if the node label is missing the then the ID is used
```

2018-12-19 16:39 UTC, conker84 commented
Mi aggiungi delle immagini su come viene mostrato il grafo?

2018-12-19 17:02 UTC, mzaratin-larus commented
![schermata del 2018-12-19 18-01-49](https://user-images.githubusercontent.com/12963830/50235466-3afc7480-03b8-11e9-89ae-344c8a31b7a6.png)

2018-12-19 17:10 UTC, mzaratin-larus commented
![schermata del 2018-12-19 18-10-15](https://user-images.githubusercontent.com/12963830/50235920-5fa51c00-03b9-11e9-931a-a27126f77057.png)

2018-12-20 08:36 UTC, closed without merging