fixes #899 - make apoc.meta.* sample at batches
larusba/neo4j-apoc-procedures pull request #43
Opened 2019-01-09 11:12 UTC by AngeloBusato

2019-01-17 21:25 UTC, conker84 requested changes

2019-01-17 21:25 UTC, conker84 commented on src/main/java/apoc/meta/Meta.java
> +    @Description("apoc.meta.data([config])  - examines a subset of the graph to provide a tabular meta information")
```suggestion
    @Description("apoc.meta.data({config})  - examines a subset of the graph to provide a tabular meta information")
```

2019-01-17 21:25 UTC, conker84 commented on src/main/java/apoc/meta/Meta.java
> +    @Description("apoc.meta.data([config])  - examines a subset of the graph to provide a tabular meta information")
Anche negli altri

2019-01-17 21:25 UTC, conker84 commented on src/main/java/apoc/meta/Meta.java
> +                if(config.getSample() == -1){
credo che questo if si possa semplificate lasciando solo l'else `<numero> % -1 == 0`

2019-01-17 21:25 UTC, conker84 commented on src/main/java/apoc/meta/Meta.java
> +            if(metaConfig.getSample() == -1) {
come sopra credo che questo if si possa semplificate lasciando solo l'else `<numero> % -1 == 0`

2019-01-17 21:25 UTC, conker84 commented on src/test/java/apoc/meta/MetaTest.java
> +    public void testMetaDataWithSample() throws Exception {
Si può fare un test al contrario? Qui test i nodi ogni 2 quindi becca quelli con _name_ e _surname_ vorrei non farglieli beccare...

2019-01-17 21:25 UTC, conker84 commented on src/test/java/apoc/meta/MetaTest.java
> +    public void testMetaSchemaWithSample() {
stessa cosa, creare test al contrario

2019-01-17 21:25 UTC, conker84 commented on docs/overview.adoc
> +| CALL apoc.meta.data([{sample:(number of each elements)}]) | examines a subset of the graph to provide a tabular meta information, with sample config the dataset is sampling
```suggestion
| CALL apoc.meta.data([{sample:<number of each elements>}]) | examines a subset of the graph to provide a tabular meta information, with sample config the dataset is sampling
```

anche sotto

2019-01-18 10:21 UTC, AngeloBusato commented
@conker84 aggiornata

2019-01-23 13:26 UTC, conker84 requested changes

2019-01-23 13:26 UTC, conker84 commented on src/main/java/apoc/meta/Meta.java
> +                        if (maxRels != -1 && maxRels-- == 0) break;
Perché `maxRels != -1` mentre prima era `maxRels-- == 0`

2019-01-23 14:17 UTC, AngeloBusato commented on src/main/java/apoc/meta/Meta.java
> +                        if (maxRels != -1 && maxRels-- == 0) break;
perchè max rels adesso è passato come parametro, quindi se non viene passato ha valore -1 di default e quinidi passa tutte le relazioni

2019-01-24 09:25 UTC, conker84 commented on src/main/java/apoc/meta/Meta.java
> +                        if (maxRels != -1 && maxRels-- == 0) break;
Ottimo

2019-01-24 09:25 UTC, conker84 approved these changes

2019-01-24 09:48 UTC, closed without merging