fixes #1047 - apoc.refactor.mergeNodes don't overwrite properties of relationships
larusba/neo4j-apoc-procedures pull request #45
Opened 2019-01-17 10:16 UTC by AngeloBusato

2019-01-17 21:34 UTC, conker84 requested changes

2019-01-17 21:34 UTC, conker84 commented on src/test/java/apoc/refactor/GraphRefactoringTest.java
> +    public void testMergeNodesAndMergeSameRelationshipWithPropertiesConfig() {
Perché?

2019-01-17 21:34 UTC, conker84 commented on src/test/java/apoc/refactor/GraphRefactoringTest.java
> +                    assertEquals("r1", r.getProperty("p"));
Perché abbiamo aggiunto questo?
Cos'è cambiato?

2019-01-17 21:34 UTC, conker84 commented on src/test/java/apoc/refactor/GraphRefactoringTest.java
> +                    assertEquals(Arrays.asList( "r2" , "r1"), Arrays.asList((String[])r.getProperty("p")));
Perché abbiamo fatto questo cambio? 
Non è uguale alla riga 564 così?

2019-01-17 21:34 UTC, conker84 commented on src/test/java/apoc/refactor/GraphRefactoringTest.java
> +
Rimuovere spazi aggiunti senza scopo

2019-01-18 09:08 UTC, AngeloBusato commented
@conker84 aggiornata

2019-01-24 09:31 UTC, conker84 approved these changes

2019-01-24 09:33 UTC, closed without merging