1044 - Drop Duplicate Neighbors
larusba/neo4j-apoc-procedures pull request #47
Opened 2019-01-23 11:23 UTC by AngeloBusato

2019-01-23 11:48 UTC, conker84 requested changes

2019-01-23 11:48 UTC, conker84 commented on src/main/java/apoc/coll/Coll.java
> +        Object[] elements = input.toArray();
Perché?
```suggestion
        Class first = input.get(0).getClass();
```

2019-01-23 11:48 UTC, conker84 commented on src/main/java/apoc/coll/Coll.java
> +            for(int i = 0; i < list.size()-1; i++) {
Spazio :)

2019-01-23 11:48 UTC, conker84 commented on src/main/java/apoc/coll/Coll.java
> +                int j = i+1;
Spazio :)

2019-01-23 11:48 UTC, conker84 commented on src/main/java/apoc/coll/Coll.java
> +                while (j < list.size() && list.get(i).equals(list.get(j))) {
I `list.get` mettili in variabili

2019-01-23 11:48 UTC, conker84 commented on src/main/java/apoc/coll/Coll.java
> +                    list.remove(list.get(j));
piuttosto che rimuovere crea una nuova collezione a aggiungi gli elementi solo se è soddisfatta la condizione di diseguaglianza.

2019-01-23 11:58 UTC, AngeloBusato commented on src/main/java/apoc/coll/Coll.java
> +                int j = i+1;
ove scusa? :)

2019-01-23 11:58 UTC, AngeloBusato commented on src/main/java/apoc/coll/Coll.java
> +            for(int i = 0; i < list.size()-1; i++) {
ove scusa? :)

2019-01-23 13:06 UTC, conker84 commented on src/main/java/apoc/coll/Coll.java
> +            for(int i = 0; i < list.size()-1; i++) {
`for(`

2019-01-23 13:07 UTC, conker84 commented on src/main/java/apoc/coll/Coll.java
> +                int j = i+1;
`i+1`

2019-01-23 15:20 UTC, AngeloBusato commented
@conker84 aggiornata

2019-01-24 09:09 UTC, conker84 requested changes

2019-01-24 09:09 UTC, conker84 commented on src/main/java/apoc/coll/Coll.java
> +        if (sameTypeForAllElements(list)) {
Con questo if cicliamo due volte la collezione, la prima per verificare che gli elementi siano dello stesso tipo e la seconda per filtrare i duplicati.
Possiamo fare tutto in un unico cliclo? Esempio:
```
boolean hasSameType = true;
List<Object> newList = new ArrayList<>();
newList.add(list.get(0));
Class first = input.get(0).getClass();
for (int i = 1; i < list.size(); i++) {
        Object element = list.get(i);
        if (!element.equals(newList.get(newList.size() - 1))) {
                if (first.isAssignableForm(element.getClass()) {
                        newList.add(element);
                } else {
                        hasSameType = false;
                        break;
                } 
        }
}
if (!hasSameType) // throw dell'eccezione
```

2019-01-24 09:09 UTC, conker84 commented on src/main/java/apoc/coll/Coll.java
> +        if (sameTypeForAllElements(list)) {
Così risparmiamo un cliclo e miglioriamo le performance nel caso di liste di grosse dimensioni

2019-01-24 09:32 UTC, AngeloBusato commented
@conker84 aggiornata

2019-01-24 09:34 UTC, conker84 approved these changes

2019-01-24 09:38 UTC, closed without merging