fixes #1040 - apoc.convert.toTree config option to include/exclude certain properties
larusba/neo4j-apoc-procedures pull request #50
Opened 2019-01-29 11:06 UTC by AngeloBusato

2019-01-29 17:02 UTC, conker84 requested changes

2019-01-29 17:02 UTC, conker84 commented on src/main/java/apoc/convert/ConvertConfig.java
> +        this.rels = (Map<String, Object>) config.getOrDefault("rels", Collections.EMPTY_MAP);
Ci vorrebbe una validazione che controlla se per ogni label o relazione ci sono solo proprietà di inclusione o esclusione

2019-01-29 17:02 UTC, conker84 commented on src/main/java/apoc/convert/Json.java
> +    public enum IncludeExclude {
Questa è la classe di validazione di cui chiedevo sopra giusto?
Mettiamo nella classe `ConvertConfig` la validazione tipo
```
boolean isFirstExclude = list.get(0).startsWith("-");
boolean hasMixedProp = false;
for (int i = 1, length = list.size(); i < length; i++) {
     String prop = list.get(i)
     if ((isFirstExclude && !prop.startsWith("-"))
               || (!isFirstExclude && prop.startsWith("-"))) { // controlla che copra tutti i casi
          hasMixedProp = true;
          break;
     }
}
if (hasMixedProp) // throw exc
```

2019-01-29 17:02 UTC, conker84 commented on src/test/java/apoc/convert/ConvertJsonTest.java
> +                " CALL apoc.convert.toTree(paths,{lowerCaseRels:false}) YIELD value RETURN value",
Mettere questo test (e gli altri simili) com'era prima e creare una procedura con la stessa firma della vecchia `apoc.convert.toTree(paths,true/false)` che chiama la nostra nuova procedura con gli opportuni parametri `apoc.convert.toTree(paths,{lowerCaseRels:true/false})`

2019-01-29 22:23 UTC, conker84 commented on src/main/java/apoc/convert/Json.java
> +    public enum IncludeExclude {
@AngeloBusato meglio ancora usiamo gli stream
```
boolean isFirstExclude = list.get(0).startsWith("-");
boolean hasMixedProp = list.stream()
     .skip(1)
     .filter(prop-> (isFirstExclude && !prop.startsWith("-"))
               || (!isFirstExclude && prop.startsWith("-"))) // controlla che copra tutti i casi
     .findFirst();
if (hasMixedProp) // throw exc
```

2019-02-05 13:52 UTC, mzaratin-larus commented on src/test/java/apoc/convert/ConvertJsonTest.java
> +                " CALL apoc.convert.toTree(paths,{lowerCaseRels:false}) YIELD value RETURN value",
Non si possono creare due procedure con lo stesse nome

2019-02-12 13:42 UTC, closed without merging