fixes #161 - Create Graph from JSON document
larusba/neo4j-apoc-procedures pull request #58
Opened 2019-02-19 14:19 UTC by AngeloBusato

2019-02-26 22:28 UTC, conker84 commented
Mi puoi mettere qualche esempio di import qui con immagini di corredo?

2019-02-27 13:33 UTC, mzaratin-larus commented
````
CALL apoc.graph.inverseToTree("{'id': 1,'type': 'artist','name':'Genesis','members': ['Tony Banks','Mike Rutherford','Phil Collins'],'years': [1967, 1998, 1999, 2000, 2006],'albums': [{'type': 'album','id': 1,'producer': 'Jonathan King','title': 'From Genesis to Revelation'}]}", false) yield graph return graph
````
![result](https://user-images.githubusercontent.com/12963830/53487929-2cec6380-3a8d-11e9-9296-9c4b1f3c8a1b.png)

````
CALL apoc.graph.inverseToTree("{'id': 1,'type': 'Person','name':'Mike','born': 1960,'friendOf': [{'type': 'Friend','id': 2,'name': 'Kate'}],'work': [{'type': 'Company','id': 3,'name': 'Neo4j'}]}", false) yield graph return graph
````
![result_1](https://user-images.githubusercontent.com/12963830/53493843-a2abfb80-3a9c-11e9-9eab-c8695e6b57fb.png)

2019-02-27 17:36 UTC, conker84 requested changes
Correggere il piccolo errore nella documentazione e pushare su contrib con le immagini di esempio

2019-02-27 17:36 UTC, conker84 commented on docs/asciidoc/virtual-graph.adoc
> +As a result we have a virtual graph two nodes with one relationship:
```suggestion
As a result we have a virtual graph with two nodes and one relationship:
```

2019-02-27 17:36 UTC, conker84 commented
Grazie mille

2019-02-28 09:08 UTC, closed without merging