Issue 568 bis
larusba/neo4j-apoc-procedures pull request #59
Opened 2019-02-25 08:20 UTC by AngeloBusato

2019-02-25 15:44 UTC, conker84 requested changes

2019-02-25 15:44 UTC, conker84 commented on src/main/java/apoc/ApocKernelExtensionFactory.java
> +            if (uuidLifeCycle !=null)
mettere le parentesi graffe per migliorare la leggibilità

2019-02-25 15:44 UTC, conker84 commented on src/main/java/apoc/uuid/UuidHandler.java
> +                        ResourceIterator<Object> result = db.execute(String.format("MATCH (n:%s) WHERE not exists(n.uuid) RETURN n", label)).columnAs("n");
perché facciamo questa query?
non possiamo fare `tx.createdNodes()` (per accedere a tutti i nodi creat) e `tx.assignedNodeProperties()` (per verificare che accidentalmente non sia stata cancellata la proprieta e in tal caso ripristinarla se era presente) nella beforeCommit e verificare se per questi è necessario aggiungere l'uuid?

2019-02-25 15:44 UTC, conker84 commented on src/main/java/apoc/uuid/Uuid.java
> +    public Stream<UuidInfo> add(@Name("name") String name, @Name("labels") List<String> labels, @Name(value = "selector", defaultValue = "{}") Map<String, Object> selector) {
Quando si aggiungere un trigger UUID va verificato se per le label definitite sono già presenti nodi e in questo caso va tenuto conto di un parametro di configurazione `addToAlreadyPresent` true/false (default: true) che fa l'aggiornamento del pregresso

2019-02-25 15:44 UTC, conker84 commented on src/main/java/apoc/uuid/UuidHandler.java
> +        executeUuid(data, "roolback");
secondo me non è necessaria gestire la `afterRollback`

2019-02-25 15:44 UTC, conker84 commented on src/main/java/apoc/uuid/UuidHandler.java
> +        executeUuid(data, "after");
secondo me non è necessaria gestire la `afterCommit`

2019-02-26 23:01 UTC, conker84 requested changes

2019-02-26 23:01 UTC, conker84 commented on src/main/java/apoc/uuid/UuidHandler.java
> +        if (selector == null) return (phase.equals("before"));
se anche `phase` è null?
```suggestion
        if (selector == null) return phase.equals("before");
```

2019-02-26 23:01 UTC, conker84 commented on src/main/java/apoc/uuid/UuidHandler.java
> +                        if (when(params, phase)) {
ma `if (when(params, phase)) {` non può essere messo fuori il `forEach`?

2019-02-26 23:01 UTC, conker84 commented on src/main/java/apoc/uuid/UuidHandler.java
> +    private static void checkConstraintUuid(List<String> labels) {
rifattorizzare tutto usando gli stream

2019-02-27 10:57 UTC, mzaratin-larus commented on src/main/java/apoc/uuid/UuidHandler.java
> +        if (selector == null) return (phase.equals("before"));
in questo caso non potrà arrivare mai a null perchè prende il valore del phase che è solo `before` in questo caso

2019-02-28 20:15 UTC, conker84 commented on src/main/java/apoc/uuid/UuidHandler.java
> +        if (selector == null) return (phase.equals("before"));
non è sufficiente fare solo `if (phase.equals("before"))`?

2019-02-28 20:17 UTC, conker84 commented on src/main/java/apoc/uuid/UuidHandler.java
> +        if (uuid.containsKey("")) updateUuid(null,null);
per favore mettere il contenuto di `executeUuid` dentro la `beforeCommit`

2019-03-01 14:35 UTC, conker84 approved these changes

2019-03-01 16:39 UTC, closed without merging