APOC Intersection issue
larusba/neo4j-apoc-procedures pull request #7
Opened 2018-07-27 14:00 UTC by AngeloBusato

2018-10-08 13:58 UTC, conker84 requested changes

2018-10-08 13:58 UTC, conker84 commented on src/main/java/apoc/coll/Coll.java
> +        for(int i = 0; i < first.size(); i++ ) { first.set(i, first.get(i).getClass().getTypeName().contains("Integer") ? Long.parseLong(first.get(i).toString()) : first.get(i));  }
Questo adesso lo possiamo rimuovere giusto? (Stessa cosa per `second`)

2018-10-08 14:05 UTC, AngeloBusato commented on src/main/java/apoc/coll/Coll.java
> +        for(int i = 0; i < first.size(); i++ ) { first.set(i, first.get(i).getClass().getTypeName().contains("Integer") ? Long.parseLong(first.get(i).toString()) : first.get(i));  }
yes

2018-10-08 14:14 UTC, AngeloBusato commented
@conker84 aggiornata

2018-10-17 17:06 UTC, conker84 commented
Ok

2018-10-17 19:21 UTC, conker84 approved these changes

2018-10-31 09:53 UTC, closed without merging